baseURL: "/" 
languageCode: en-us
defaultContentLanguage: en
title: Principles of Ecology 
theme: "cupper-hugo-theme"
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: false

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Course (BIOL4253) at LSU.
  homeMetaContent: Principles of Ecology.
  footer: 
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  moveFooterToHeader: true
  logoAlt: "A logo for the Principles of Ecology course"
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Home 
      url: /
      weight: 1
    - name: Syllabus 
      url: /syllabus/
      weight: 2
    - name: Final project
      url: /project/
      weight: 3
    - name: Schedule & Materials
      url: /schedule_materials/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
